name: action_cable
version: 1.1.0
description: >-
  ActionCable client port in dart, available in web, dartVM and flutter.
homepage: https://github.com/namiwang/actioncable_dart
documentation: https://github.com/namiwang/actioncable_dart
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  web_socket_channel: ^1.2.0
dev_dependencies:
  test:
